# Generated by Django 5.2.17 on 2026-09-28 21:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionFormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(max_length=50, unique=True, verbose_name='Número de Cotización Oficial (ej: COT-HUMM-2026-0001)')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('validez_dias', models.PositiveIntegerField(default=30, verbose_name='Días de Validez Comercial')),
                ('subtotal_neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('costo_despacho', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('condiciones_comerciales', models.TextField(blank=True, verbose_name='Condiciones Comerciales y Despacho')),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='cotizaciones_pdf/', verbose_name='PDF Oficial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cotización Formal Humm',
                'verbose_name_plural': 'Cotizaciones Formales Humm',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguimiento', models.CharField(db_index=True, help_text='Identificador amigable entregado al profesor (ej: SOL-2026-A1B2).', max_length=32, unique=True, verbose_name='Código de Seguimiento')),
                ('nombre_solicitante', models.CharField(max_length=150, verbose_name='Nombre del Solicitante / Profesor')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono / WhatsApp')),
                ('establecimiento', models.CharField(max_length=200, verbose_name='Colegio / Establecimiento Educacional')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
                ('institucion_responsable_compra', models.CharField(blank=True, max_length=200, verbose_name='Institución Responsable de Compra (si difiere, ej: DAEM, Corporación)')),
                ('contacto_adquisiciones_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre Encargado de Compras (Opcional)')),
                ('contacto_adquisiciones_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Encargado de Compras (Opcional)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del Profesor')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva solicitud recibida'), ('en_revision', 'En revisión técnica / stock'), ('cotizacion_preparada', 'Cotización formal preparada'), ('cotizacion_enviada', 'Cotización enviada al solicitante'), ('esperando_proceso_compra', 'Esperando gestión de compra / DAEM'), ('proceso_publicado', 'Proceso publicado en Mercado Público'), ('oferta_presentada', 'Oferta Humm presentada en Mercado Público'), ('adjudicada', 'Adjudicada a Humm'), ('orden_compra_recibida', 'Orden de Compra recibida'), ('en_preparacion', 'En preparación / Bodega'), ('despachada', 'Despachada a destino'), ('cerrada', 'Cerrada exitosamente'), ('cancelada_perdida', 'Cancelada / Desestimada')], db_index=True, default='nueva', max_length=40, verbose_name='Estado')),
                ('total_referencial_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Referencial Estimado (CLP)')),
                ('id_licitacion_mp', models.CharField(blank=True, max_length=50, verbose_name='ID Licitación Mercado Público')),
                ('id_compra_agil_mp', models.CharField(blank=True, max_length=50, verbose_name='ID Compra Ágil Mercado Público')),
                ('id_orden_compra_mp', models.CharField(blank=True, max_length=50, verbose_name='ID Orden de Compra Mercado Público')),
                ('notas_internas_humm', models.TextField(blank=True, verbose_name='Bitácora / Notas Internas Humm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Solicitud de Cotización',
                'verbose_name_plural': 'Solicitudes de Cotización',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tecnica_neutra_utilizada', models.TextField(help_text='Texto neutro oficial incluido en el documento entregado al colegio. Sin marcas comerciales ni SKUs de fabricante.', verbose_name='Descripción Técnica Neutra Utilizada')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unidad_medida', models.CharField(default='unidad', max_length=50, verbose_name='Unidad')),
                ('precio_unitario_neto_definitivo', models.DecimalField(decimal_places=2, help_text='Precio fijado y validado por el administrador Humm para esta cotización específica.', max_digits=12, verbose_name='Precio Unitario Neto Definitivo (CLP)')),
                ('subtotal_neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal Neto (CLP)')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.cotizacionformal', verbose_name='Cotización Formal')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.producto', verbose_name='Producto de Origen (Trazabilidad Interna)')),
            ],
            options={
                'verbose_name': 'Ítem de Cotización Formal',
                'verbose_name_plural': 'Ítems de Cotización Formal',
            },
        ),
        migrations.AddField(
            model_name='cotizacionformal',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_formal', to='cotizaciones.solicitudcotizacion', verbose_name='Solicitud de Origen'),
        ),
        migrations.CreateModel(
            name='SolicitudItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_humm_snapshot', models.CharField(max_length=64, verbose_name='SKU Humm (Snapshot)')),
                ('marca_snapshot', models.CharField(max_length=100, verbose_name='Marca (Snapshot)')),
                ('modelo_snapshot', models.CharField(blank=True, max_length=100, verbose_name='Modelo (Snapshot)')),
                ('nombre_comercial_snapshot', models.CharField(max_length=255, verbose_name='Nombre Comercial (Snapshot)')),
                ('especificacion_neutra_snapshot', models.TextField(blank=True, help_text='Copia inmutable de la especificación técnica neutra vigente al cotizar.', verbose_name='Especificación Neutra (Snapshot)')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_referencial_unitario_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio Referencial Unitario Sugerido (Snapshot)')),
                ('subtotal_referencial_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal Referencial (Snapshot)')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_item', to='catalogo.producto', verbose_name='Producto de Referencia')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.solicitudcotizacion', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Ítem de Solicitud',
                'verbose_name_plural': 'Ítems de Solicitud',
            },
        ),
    ]
