# Generated by Django 5.2.17 on 2026-09-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='cargo_solicitante',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo o Rol del Solicitante'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='fecha_requerida_aproximada',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fecha Aproximada Requerida'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='proyecto_educativo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre o Finalidad del Proyecto Educativo'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='tipo_institucion',
            field=models.CharField(blank=True, help_text='Dependencia institucional informada (ej: Municipal/SLEP, Particular Subvencionado, etc.)', max_length=60, verbose_name='Tipo de Institución'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True, verbose_name='Token de Confirmación Pública'),
        ),
        migrations.AddField(
            model_name='solicituditem',
            name='unidad_comercial_snapshot',
            field=models.CharField(default='unidad', help_text='Unidad de venta comercial congelada (ej: unidad, pack (3 unidades), set (120 cables)).', max_length=50, verbose_name='Unidad Comercial (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='codigo_seguimiento',
            field=models.CharField(db_index=True, help_text='Identificador comercial amigable entregado al profesor (ej: EC-2026-A1B2C3).', max_length=32, unique=True, verbose_name='Código de Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='estado',
            field=models.CharField(choices=[('NUEVA', 'Nueva solicitud recibida'), ('EN_REVISION', 'En revisión técnica / stock'), ('REQUIERE_ANTECEDENTES', 'Requiere contactar al docente por antecedentes'), ('LISTA_PARA_COTIZAR', 'Lista para emitir cotización'), ('COTIZACION_PREPARADA', 'Cotización formal preparada'), ('COTIZACION_ENVIADA', 'Cotización enviada al colegio'), ('CERRADA', 'Cerrada exitosamente (Venta realizada)'), ('PERDIDA', 'Desestimada / Perdida'), ('CANCELADA', 'Cancelada por el solicitante')], db_index=True, default='NUEVA', max_length=40, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones / Comentarios del Profesor'),
        ),
    ]
