# Generated by Django 5.2.17 on 2026-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_solicitudcotizacion_cargo_solicitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituditem',
            name='sku_proveedor_snapshot',
            field=models.CharField(blank=True, max_length=64, verbose_name='SKU Proveedor (Snapshot)'),
        ),
    ]
