# Generated by Django 5.2.17 on 2026-09-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_solicituditem_sku_proveedor_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='rut_institucion',
            field=models.CharField(blank=True, max_length=20, verbose_name='RUT Institución (Opcional)'),
        ),
    ]
