# Generated by Django 5.2.17 on 2026-09-30 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_solicitudcotizacion_rut_institucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo o Rol')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono / WhatsApp')),
                ('es_encargado_compras', models.BooleanField(default=False, verbose_name='Es Encargado de Compras')),
                ('posible_duplicado', models.BooleanField(default=False, verbose_name='Requiere Revisión de Duplicado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('primera_interaccion', models.DateTimeField(blank=True, null=True, verbose_name='Primera Interacción')),
                ('ultima_interaccion', models.DateTimeField(blank=True, null=True, verbose_name='Última Interacción')),
                ('observaciones_internas', models.TextField(blank=True, verbose_name='Observaciones Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacto Docente / Institucional',
                'verbose_name_plural': 'Contactos Docentes / Institucionales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200, verbose_name='Nombre de la Institución')),
                ('nombre_normalizado', models.CharField(blank=True, db_index=True, editable=False, max_length=200)),
                ('rut', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='RUT Institución')),
                ('rbd', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='RBD Mineduc')),
                ('tipo_institucion', models.CharField(blank=True, choices=[('MUNICIPAL_SLEP', 'Municipal / Servicio Local de Educación (SLEP)'), ('PARTICULAR_SUBVENCIONADO', 'Particular Subvencionado'), ('PARTICULAR_PAGADO', 'Particular Pagado'), ('CORPORACION_FUNDACION', 'Corporación / Fundación Educativa'), ('EDUCACION_SUPERIOR', 'CFT / IP / Universidad'), ('OTRO', 'Otro tipo de institución')], max_length=60, verbose_name='Tipo de Institución')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('region', models.CharField(db_index=True, max_length=100, verbose_name='Región')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('estado_conciliacion', models.CharField(choices=[('CONCILIADO', 'Conciliado formal'), ('PENDIENTE_CONCILIACION', 'Pendiente de conciliación manual')], db_index=True, default='CONCILIADO', max_length=30)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('primera_interaccion', models.DateTimeField(blank=True, null=True, verbose_name='Primera Interacción')),
                ('ultima_interaccion', models.DateTimeField(blank=True, null=True, verbose_name='Última Interacción')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas Internas Humm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Establecimiento Educacional',
                'verbose_name_plural': 'Establecimientos Educacionales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='es_prueba',
            field=models.BooleanField(db_index=True, default=False, help_text='Marcar para excluir de métricas comerciales e indicadores del Dashboard.', verbose_name='Es Solicitud de Prueba Interna'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre Comercial'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='fuente_origen',
            field=models.CharField(blank=True, default='Directo', max_length=100, verbose_name='Fuente de Tráfico'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='monto_final_vendido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Monto Final Vendido (CLP)'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Comercial Humm'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='subestado_cierre',
            field=models.CharField(blank=True, choices=[('EN_NEGOCIACION', 'En negociación final'), ('ADJUDICADA_MP', 'Adjudicada en Mercado Público'), ('ORDEN_COMPRA_RECIBIDA', 'Orden de Compra recibida'), ('FACTURADA', 'Facturada'), ('PAGADA', 'Pagada / Completada')], max_length=50, verbose_name='Sub-estado de Cierre Comercial'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=150, verbose_name='UTM Campaign'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='utm_content',
            field=models.CharField(blank=True, max_length=150, verbose_name='UTM Content'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM Medium'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM Source'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='contacto_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='cotizaciones.contacto', verbose_name='Contacto Docente Principal'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='establecimiento_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='cotizaciones.establecimiento', verbose_name='Establecimiento Principal'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='establecimiento_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='cotizaciones.establecimiento', verbose_name='Establecimiento Relacionado'),
        ),
    ]
