# Generated by Django 5.2.17 on 2026-09-28 21:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio_usd_clp', models.DecimalField(decimal_places=2, default=Decimal('950.00'), help_text='Valor referencial del dólar para calcular costos en pesos chilenos.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Tipo de Cambio (USD a CLP)')),
                ('recargo_general_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Porcentaje de margen sugerido sobre el costo internado (ej: 80.00%). Administrable, no codificado rígidamente.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Recargo Comercial Sugerido (%)')),
                ('factor_internacion_flete_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Porcentaje estimado de costos de aduana y transporte internacional.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Factor Estimado de Flete e Internación (%)')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Porcentaje de Impuesto al Valor Agregado en Chile (19%).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='IVA (%)')),
                ('email_notificaciones_humm', models.EmailField(default='contacto@humm.cl', help_text='Dirección de correo que recibe avisos cuando un profesor solicita cotización.', max_length=254, verbose_name='Email Notificaciones Humm')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Parámetros de Pricing y Configuración',
                'verbose_name_plural': 'Parámetros de Pricing y Configuración',
            },
        ),
    ]
