# Generated by Django 5.2.17 on 2026-09-29 16:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionpricing',
            name='recargo_general_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Porcentaje de recargo comercial sugerido sobre el costo internado (ej: 80.00%). Administrable, no codificado rígidamente.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Recargo Comercial Sugerido (%)'),
        ),
    ]
