# Generated by Django 5.2.17 on 2026-09-30 16:46

import django.core.files.storage
import django.db.models.deletion
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0005_producto_slug'),
        ('cotizaciones', '0005_contacto_establecimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_excel', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/rmerinog/PLATAFORMAS/EDUCOMPRA/private_storage')), upload_to='excel/%Y/%m/', verbose_name='Archivo Excel (.xlsx / .xls)')),
                ('archivo_imagenes_zip', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/rmerinog/PLATAFORMAS/EDUCOMPRA/private_storage')), upload_to='zip/%Y/%m/', verbose_name='Archivo ZIP de Imágenes')),
                ('estado', models.CharField(choices=[('SUBIDO', 'Archivo subido — Pendiente DRY-RUN'), ('SIMULADO', 'DRY-RUN completado con éxito'), ('CON_CONFLICTOS', 'DRY-RUN completado con advertencias/conflictos'), ('APROBADO', 'Aprobado para importación'), ('APLICADO', 'Importación productiva ejecutada'), ('FALLIDO', 'Error en ejecución')], db_index=True, default='SUBIDO', max_length=30, verbose_name='Estado')),
                ('es_dry_run', models.BooleanField(default=True, verbose_name='Es Simulación (DRY-RUN)')),
                ('filas_leidas', models.PositiveIntegerField(default=0, verbose_name='Filas Leídas')),
                ('skus_detectados', models.PositiveIntegerField(default=0, verbose_name='SKUs Detectados')),
                ('productos_nuevos', models.PositiveIntegerField(default=0, verbose_name='Productos Nuevos')),
                ('productos_actualizados', models.PositiveIntegerField(default=0, verbose_name='Productos Actualizados')),
                ('productos_sin_cambios', models.PositiveIntegerField(default=0, verbose_name='Productos sin Cambios')),
                ('conflictos_detectados', models.PositiveIntegerField(default=0, verbose_name='Conflictos Detectados')),
                ('productos_sin_imagen', models.PositiveIntegerField(default=0, verbose_name='Productos sin Imagen')),
                ('imagenes_sin_producto', models.PositiveIntegerField(default=0, verbose_name='Imágenes sin Producto')),
                ('resumen_json', models.JSONField(blank=True, default=dict, verbose_name='Resumen JSON')),
                ('registro_conflictos_md', models.TextField(blank=True, verbose_name='Registro de Conflictos Markdown')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Subió el Lote')),
            ],
            options={
                'verbose_name': 'Lote de Importación',
                'verbose_name_plural': 'Lotes de Importación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('PUBLICAR_PRODUCTO', 'Publicar Producto'), ('DESPUBLICAR_PRODUCTO', 'Despublicar Producto'), ('CREAR_PRODUCTO', 'Crear Producto Manual'), ('EDITAR_PRODUCTO', 'Editar Ficha de Producto'), ('EDITAR_PRECIO', 'Cambio de Precio / Costo'), ('CAMBIO_ESTADO_SOLICITUD', 'Cambio de Estado de Solicitud'), ('ASIGNAR_RESPONSABLE', 'Asignación de Responsable Humm'), ('ACTUALIZAR_NOTAS_SOLICITUD', 'Actualización de Bitácora Solicitud'), ('VALIDAR_TECNICA', 'Validación Técnica Neutra'), ('IMPORTACION_DRY_RUN', 'Simulación DRY-RUN de Catálogo'), ('IMPORTACION_EJECUTADA', 'Importación Productiva de Catálogo'), ('MODIFICAR_PRICING', 'Modificación de Parámetros de Pricing'), ('RECALCULAR_PRECIOS_MASIVO', 'Recálculo Masivo de Precios'), ('CONCILIACION_ESTABLECIMIENTOS', 'Ejecución de Conciliación Histórica')], db_index=True, max_length=60, verbose_name='Acción')),
                ('modelo_afectado', models.CharField(max_length=60, verbose_name='Modelo Afectado')),
                ('objeto_id', models.CharField(blank=True, max_length=60, verbose_name='ID Objeto')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción de la Acción')),
                ('detalles', models.JSONField(blank=True, default=dict, help_text='Registro de cambios (valor anterior/nuevo). Cero contraseñas, secretos o datos sensibles.', verbose_name='Detalles Estructurados')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origen')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-created_at'],
                'permissions': [('can_view_gestion', 'Puede acceder a la plataforma de administración EduCompra'), ('can_manage_catalogo', 'Puede administrar catálogo de productos'), ('can_publish_producto', 'Puede publicar o despublicar productos'), ('can_run_importaciones', 'Puede ejecutar importaciones masivas de catálogo'), ('can_manage_solicitudes', 'Puede gestionar solicitudes comerciales'), ('can_manage_cotizaciones', 'Puede gestionar cotizaciones formales'), ('can_manage_establecimientos', 'Puede gestionar establecimientos y contactos'), ('can_view_analitica', 'Puede visualizar analítica y telemetría'), ('can_manage_configuracion', 'Puede modificar parámetros de pricing y configuración')],
            },
        ),
        migrations.CreateModel(
            name='EventoUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('VISITA', 'Visita a página pública'), ('BUSQUEDA', 'Búsqueda en catálogo'), ('VER_PRODUCTO', 'Visualización de ficha de producto'), ('AGREGAR_COTIZACION', 'Producto agregado a Mi Cotización'), ('QUITAR_COTIZACION', 'Producto retirado de Mi Cotización'), ('VER_MI_COTIZACION', 'Visualización de canasta'), ('INICIAR_SOLICITUD', 'Formulario de solicitud abierto'), ('ENVIAR_SOLICITUD', 'Solicitud de cotización enviada exitosamente')], db_index=True, max_length=30)),
                ('session_hash', models.CharField(db_index=True, help_text='Identificador irreversible generado con secreto de servidor. Nunca almacena la session_key real.', max_length=64, verbose_name='Hash Seudónimo de Sesión (HMAC-SHA256)')),
                ('termino_busqueda', models.CharField(blank=True, db_index=True, max_length=255)),
                ('termino_busqueda_normalizado', models.CharField(blank=True, db_index=True, max_length=255)),
                ('resultados_busqueda', models.PositiveIntegerField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, max_length=100, verbose_name='Fuente / Referrer')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=150, verbose_name='UTM Campaign')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Solo claves autorizadas de navegación. Prohibido almacenar datos personales o secretos.', verbose_name='Metadata Controlada')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_uso', to='catalogo.categoria', verbose_name='Categoría Asociada')),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_asociados', to='cotizaciones.establecimiento', verbose_name='Establecimiento Asociado')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_uso', to='catalogo.producto', verbose_name='Producto Asociado')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_asociados', to='cotizaciones.solicitudcotizacion', verbose_name='Solicitud Asociada')),
            ],
            options={
                'verbose_name': 'Evento de Uso',
                'verbose_name_plural': 'Eventos de Uso',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipo_evento', 'created_at'], name='gestion_eve_tipo_ev_48a451_idx'), models.Index(fields=['session_hash', 'created_at'], name='gestion_eve_session_86ee5c_idx'), models.Index(fields=['producto', 'tipo_evento'], name='gestion_eve_product_aae32e_idx'), models.Index(fields=['termino_busqueda_normalizado', 'resultados_busqueda'], name='gestion_eve_termino_b0517d_idx')],
            },
        ),
    ]
