# Generated by Django 5.2.17 on 2026-09-28 21:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug URL')),
                ('icono_svg', models.TextField(blank=True, verbose_name='Icono SVG / Identificador')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción Corta')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de Despliegue')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Proveedor')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Interno (ej: KEY)')),
                ('moneda_origen', models.CharField(default='USD', max_length=10, verbose_name='Moneda Origen')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_humm', models.CharField(help_text='Identificador único interno de Humm (ej: HUMM-ARD-001).', max_length=64, unique=True, verbose_name='SKU Humm')),
                ('sku_proveedor', models.CharField(db_index=True, help_text='Código del fabricante (ej: KS0011). Utilizado para mapeo de imágenes y actualización de costos.', max_length=64, verbose_name='SKU Proveedor')),
                ('marca', models.CharField(default='Keyestudio', max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('nombre_comercial', models.CharField(help_text='Nombre amigable presentado al docente (ej: Sensor de Humedad de Suelo Keyestudio KS0011).', max_length=255, verbose_name='Nombre Comercial')),
                ('nombre_original_proveedor', models.CharField(blank=True, max_length=255, verbose_name='Nombre Original en Catálogo Fabricante')),
                ('descripcion_corta', models.CharField(blank=True, max_length=300, verbose_name='Descripción Corta')),
                ('descripcion_educativa', models.TextField(blank=True, help_text='Texto explicativo para el profesor: aplicaciones pedagógicas, proyectos posibles con estudiantes y compatibilidad.', verbose_name='Descripción Pedagógica / Educativa')),
                ('unidad_compra', models.CharField(default='unidad', max_length=50, verbose_name='Unidad de Medida')),
                ('titulo_especificacion_neutral', models.CharField(blank=True, help_text='Denominación genérica sin marca ni modelo (ej: Módulo Sensor de Humedad para Suelo).', max_length=255, verbose_name='Título Neutro para Compra Pública')),
                ('especificacion_tecnica_neutral', models.TextField(blank=True, help_text='Descripción funcional y eléctrica sin marcas ni SKUs que permite equivalencias técnicas según Ley 19.886.', verbose_name='Especificación Técnica Neutra')),
                ('criterios_equivalencia', models.TextField(blank=True, default='O producto técnicamente equivalente compatible.', verbose_name='Criterios y Cláusula de Equivalencia Técnica')),
                ('costo_proveedor_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo Proveedor (USD)')),
                ('costo_puesto_chile_clp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Costo Estimado Puesto en Chile (CLP)')),
                ('porcentaje_recargo', models.DecimalField(blank=True, decimal_places=2, help_text='Si se deja vacío, se aplicará el Recargo General configurado en los parámetros de pricing.', max_digits=6, null=True, verbose_name='Recargo Específico (%)')),
                ('precio_sugerido_neto_clp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio Sugerido Neto (CLP)')),
                ('precio_sugerido_total_clp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio referencial que visualiza el profesor en el catálogo.', max_digits=12, verbose_name='Precio Referencial Sugerido con IVA (CLP)')),
                ('publicado', models.BooleanField(db_index=True, default=False, help_text='Indica si este producto forma parte del catálogo activo curado para colegios.', verbose_name='Publicado en EduCompra')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo en Sistema')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado en Portada')),
                ('estado_stock', models.CharField(choices=[('disponible', 'Disponible entrega inmediata'), ('importacion', 'A pedido / Importación (15-20 días)'), ('consultar', 'Consultar disponibilidad')], default='disponible', max_length=50, verbose_name='Disponibilidad')),
                ('dias_entrega_estimados', models.PositiveIntegerField(default=5, verbose_name='Días de Entrega Estimados')),
                ('observaciones_internas', models.TextField(blank=True, verbose_name='Observaciones Internas Humm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.categoria', verbose_name='Categoría')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-destacado', 'nombre_comercial'],
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(blank=True, null=True, upload_to='catalogo/originales/', verbose_name='Archivo de Imagen')),
                ('nombre_archivo_original', models.CharField(blank=True, max_length=255, verbose_name='Nombre Original del Archivo (ej: KS0011.jpg)')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Imagen Principal')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['-es_principal', 'orden', 'id'],
            },
        ),
    ]
