# Generated by Django 5.2.17 on 2026-09-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnologiaCompatible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tecnología Compatible')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug URL')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de Despliegue')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Tecnología Compatible',
                'verbose_name_plural': 'Tecnologías Compatibles',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='apto_para_kit',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si este producto es un componente potencial para kits temáticos de Humm.', verbose_name='Apto para Kits Educativos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado_curaduria',
            field=models.CharField(choices=[('SIN_REVISAR', 'Sin revisar'), ('CANDIDATO', 'Candidato a catálogo público'), ('DESCARTADO_CATALOGO_PUBLICO', 'Descartado para catálogo público (conservar en maestro)'), ('EN_CURADURIA', 'En proceso de curaduría pedagógica'), ('VALIDADO', 'Curaduría pedagógica validada'), ('LISTO_PARA_PUBLICAR', 'Listo para publicar')], db_index=True, default='SIN_REVISAR', help_text='Estado del proceso de evaluación pedagógica y selección para el catálogo público.', max_length=35, verbose_name='Estado de Curaduría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado_especificacion_neutral',
            field=models.CharField(choices=[('NO_REVISADO', 'No revisado (Borrador automático)'), ('BORRADOR', 'En redacción técnica'), ('VALIDADO_HUMM', 'Validado técnicamente por Humm (Apto compra pública)')], db_index=True, default='NO_REVISADO', help_text='Validación de neutralidad técnica para compra pública. Requiere VALIDADO_HUMM para emitir cotización formal.', max_length=20, verbose_name='Estado Especificación Neutra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nivel_dificultad',
            field=models.CharField(choices=[('NO_DEFINIDO', 'No definido'), ('INICIAL', 'Inicial'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='NO_DEFINIDO', help_text='Complejidad técnica del uso del componente (Inicial, Intermedio, Avanzado).', max_length=20, verbose_name='Nivel de Dificultad / Uso'),
        ),
        migrations.AddField(
            model_name='producto',
            name='uso_educativo',
            field=models.TextField(blank=True, help_text='¿Qué podrían hacer o aprender los estudiantes con este producto?', verbose_name='Uso Educativo y Proyectos de Aula'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion_educativa',
            field=models.TextField(blank=True, help_text='Texto explicativo para el profesor: qué es, para qué sirve y contexto de aplicación.', verbose_name='Descripción Pedagógica / Educativa'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_comercial',
            field=models.CharField(help_text='Nombre amigable presentado al docente (ej: Sensor de Humedad de Suelo Keyestudio para Arduino).', max_length=255, verbose_name='Nombre Comercial'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku_humm',
            field=models.CharField(help_text='Identificador único interno de Humm (ej: HUMM-KEY-KS0011).', max_length=64, unique=True, verbose_name='SKU Humm'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tecnologias_compatibles',
            field=models.ManyToManyField(blank=True, help_text='Plataformas microcontroladoras o computacionales compatibles.', related_name='productos', to='catalogo.tecnologiacompatible', verbose_name='Tecnologías Compatibles'),
        ),
    ]
