# Generated by Django 5.2.17 on 2026-09-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_tecnologiacompatible_producto_apto_para_kit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_revision_tecnica',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Revisión Técnica'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fuente_tecnica',
            field=models.CharField(blank=True, help_text='Hoja de datos, wiki oficial o manual del fabricante.', max_length=255, verbose_name='Fuente Técnica / Fabricante'),
        ),
        migrations.AddField(
            model_name='producto',
            name='observaciones_tecnicas',
            field=models.TextField(blank=True, help_text='Evidencias, notas de laboratorio o pruebas físicas.', verbose_name='Observaciones de Validación Técnica'),
        ),
        migrations.AddField(
            model_name='producto',
            name='referencia_tecnica_url',
            field=models.URLField(blank=True, help_text='Enlace a documentación técnica verificable.', verbose_name='URL de Referencia Técnica'),
        ),
        migrations.AddField(
            model_name='producto',
            name='responsable_revision_tecnica',
            field=models.CharField(blank=True, max_length=150, verbose_name='Responsable de Validación Técnica'),
        ),
    ]
