# Generated by Django 5.2.17 on 2026-09-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_producto_fecha_revision_tecnica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='advertencia_uso',
            field=models.TextField(blank=True, help_text='Advertencia de seguridad o condiciones pedagógicas de uso (voltaje, gases, fuego, uso médico, supervisión).', verbose_name='Advertencia de Uso Educativo / Seguridad'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tecnologias_verificadas',
            field=models.ManyToManyField(blank=True, help_text='Compatibilidad técnica respaldada explícitamente por el fabricante o evidencia registrada.', related_name='productos_verificados', to='catalogo.tecnologiacompatible', verbose_name='Tecnologías Compatibles Verificadas'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tecnologias_compatibles',
            field=models.ManyToManyField(blank=True, help_text='Plataformas compatibles propuestas pedagógicamente para proyectos de aula.', related_name='productos', to='catalogo.tecnologiacompatible', verbose_name='Tecnologías Compatibles Propuestas'),
        ),
    ]
