# Generated by Django 5.2.17 on 2026-09-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_producto_advertencia_uso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador semántico para URL amigable del catálogo.', max_length=150, null=True, unique=True, verbose_name='Slug URL'),
        ),
    ]
