# Generated by Django 5.2.17 on 2026-09-30 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_producto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='features_proveedor',
            field=models.TextField(blank=True, help_text='Características técnicas y pedagógicas originales entregadas por el proveedor en la lista comercial. No se copian directamente al frontend público.', verbose_name='Features del Proveedor'),
        ),
        migrations.CreateModel(
            name='PrecioProveedorTramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_minima', models.PositiveIntegerField(verbose_name='Cantidad Mínima (Desde)')),
                ('cantidad_maxima', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad Máxima (Hasta)')),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario Proveedor (USD)')),
                ('es_anomalo', models.BooleanField(default=False, help_text='True si el precio es mayor al tramo de menor volumen.', verbose_name='Es Anómalo')),
                ('estado_validacion', models.CharField(choices=[('VALIDO', 'Válido (Escala lógica no creciente)'), ('PRECIO_PROVEEDOR_REQUIERE_REVISION', 'Requiere revisión (Anomalía detectada)')], default='VALIDO', max_length=45, verbose_name='Estado de Validación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_tramos', to='catalogo.producto', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precios_tramos', to='catalogo.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Tramo de Precio Proveedor',
                'verbose_name_plural': 'Tramos de Precios Proveedor',
                'ordering': ['producto', 'cantidad_minima'],
                'unique_together': {('producto', 'proveedor', 'cantidad_minima')},
            },
        ),
    ]
