# Generated by Django 5.2.17 on 2026-09-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_producto_features_proveedor_precioproveedortramo'),
    ]

    operations = [
        migrations.AddField(
            model_name='precioproveedortramo',
            name='notas_validacion',
            field=models.TextField(blank=True, verbose_name='Notas de Validación / Motivo Anomalía'),
        ),
        migrations.AlterField(
            model_name='precioproveedortramo',
            name='estado_validacion',
            field=models.CharField(choices=[('VALIDADO', 'Validado (Escala lógica no creciente)'), ('VALIDO', 'Válido (Escala lógica no creciente)'), ('PRECIO_PROVEEDOR_REQUIERE_REVISION', 'Requiere revisión (Anomalía detectada)')], default='VALIDADO', max_length=45, verbose_name='Estado de Validación'),
        ),
    ]
