# Generated by Django 5.2.17 on 2026-10-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_precioproveedortramo_notas_validacion_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('proveedor', 'sku_proveedor'), name='unique_proveedor_sku_proveedor'),
        ),
    ]
